# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Install Github CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Fetch previous tag
      id: prev-tag
      run: |
        prev_tag=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
        if [ -z "$prev_tag" ]; then
          echo "No previous tag found"
        else
          echo "Previous tag: $prev_tag"
        fi
        echo "::set-output name=prev_tag::$prev_tag"
