# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js and React CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  backend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependences
      run: npm install
      working-directory: ./

    - name: Build backend
      run: npm run build --if-present
      working-directory: ./

    - name: Run ESLint
      run: npm run lint
      working-directory: ./

    - name: Run test
      run: npm run test
      working-directory: ./

  frontend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependences
      run: npm install
      working-directory: ./frontend

    - name: Build backend
      run: npm run build --if-present
      working-directory: ./frontend

    - name: Run ESLint
      run: npm run lint
      working-directory: ./frontend

    - name: Run test
      run: npm run test
      working-directory: ./frontend
    
